config/routes.rb
Rails.application.routes.draw do
  get 'init', to: "game#init"
  get 'score', to: "game#score"
  get 'game', to: "game#game"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
require 'open-uri'
require 'json'

class GameController < ApplicationController
  def score
    @attempt = params[:attempt]
    @grid_sent = params[:grid]
    @start_time = Time.parse(params[:start_time])
    @score = run_game(@attempt, @grid_sent, @start_time, Time.now)[:score]
    @message = run_game(@attempt, @grid_sent, @start_time, Time.now)[:message]
    @time = run_game(@attempt, @grid_sent, @start_time, Time.now)[:time]
    session[:games] += 1
  end

  def game
    @grid = generate_grid(8)
    @number_of_games = session[:games]
    session[:username] = params[:username]
    @player = session[:username]
  end

  def init
    session[:games] = 0
  end

  private

  def generate_grid(grid_size)
    # TODO: generate random grid of letters
    grid = []
    (1..grid_size).to_a.each { |_i| grid << ('A'..'Z').to_a.sample }
    return grid
  end

  def run_game(attempt, grid, start_time, end_time)
    # TODO: runs the game and return detailed hash of result
    result = {}
    result[:score] = 0
    result[:time] = end_time - start_time
    grid = eval(grid)
    if word_is_english?(attempt) && word_in_grid?(attempt, grid)
      result[:message] = "well done!"
      result[:score] = attempt.size + [(start_time - end_time)/100, -3].max
    else
      result[:message] = "Sorry, this is not an english word!" if word_is_english?(attempt) == false
      result[:message] = "Sorry, this word is not in the grid!" if word_in_grid?(attempt, grid) == false
    end
    return result
  end

  def word_is_english?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}").read
    parsed = JSON.parse(response)
    if parsed["found"] == true
      return true
    else return false
    end
  end

  def word_in_grid?(word, grid)
    hash_grid = {}
    grid.each { |letter| hash_grid[letter] = hash_grid[letter].to_i + 1 }
    word.upcase.split('').each { |letter| hash_grid[letter] = hash_grid[letter].to_i - 1 }
    return hash_grid.none? { |_k, v| v < 0 }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/game.html.erb
<div class="header-game">
  <div class="history">
    <h4><%= @player %>'s Past Games</h4>
    <p># games played: <%= @number_of_games %></p>
    <p>avg score: TODO</p>
  </div>
  <div class="title text-center">
    <h1>Longest word game</h1>
  </div>
  <div class="time text-right">
    <h4>Play as fast as you can</h4>
    <p>start time: <%= Time.now.strftime("%Hh%Mmin%Ssec") %></p>
    <p>current time: #TODO set a timer</p>
  </div>
</div>

<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3 core-game">
      <div class="form-group">
        <h4>Create the longest word you can!</h4>
      </div>
      <div class="form-group">
        <% @grid.each do |letter| %>
          <button class="btn btn-default btn-grid"> <%= letter %></button>
        <% end %>
      </div>
      <form action="/score" method="get">
        <div class="form-group" id="attempt-center">
          <input type="question" class="form-control text-center" name="attempt" id="attempt" placeholder="your best shot">
          <input type="hidden" class="form-control" name="grid" id="grid" value="<%= @grid %>">
          <input type="hidden" class="form-control" name="start_time" id="start_time" value="<%= Time.now %>">
        </div>
        <button type="submit" class="btn btn-danger">Check my score</button>
      </form>
    </div>
  </div>
</div>

app/views/game/init.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3 core-game">
      <div class="form-group">
        <h4>Please enter your name</h4>
      </div>
      <form action="/game" method="get">
        <div class="form-group">
          <input type="question" class="form-control text-center" name="username" id="attempt" placeholder="your name">
          <input type="hidden" class="form-control" name="number_of_games" value="<%= 0 %>">
        </div>
        <button type="submit" class="btn btn-danger">Start playing</button>
      </form>
    </div>
  </div>
</div>

app/views/game/score.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <h1> Your Result </h1>
      <p>your word: <%= @attempt %></p>
      <p>your grid: <%= @grid_sent %></p>
      <p>your time: <%= "#{@time.round} sec" %></p>
      <p>your score: <%= @score %></p>
      <p>your message: <%= @message %></p>
      <%= link_to "Play again", game_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>